### ISSUE TITLE
Choice of DB

### ISSUE THREAD

**Issue by whoback** [MuckRock/cfb#6]
I was thinking after our discussion last night about choice of DB we may want to consider SQLite. It seems to fit our use case well, is extremely low setup/maintenance/dependency, and would minimize the hassle of config/deployment when moving to production env. Thoughts? @egfrank @morisy @nmd1

**Comment by morisy** [comment]
So that generally sounds reasonable (only Flask apps I've built used SQLite and it worked well, but none were production quality projects), but I'll just throw out some considerations:

* Should we decide where to host before picking the DB? It seems like Heroku and SQLite don't play well, for example: https://devcenter.heroku.com/articles/sqlite3 After discussions last night, I think it makes sense to just pick a host (I'm in favor of Heroku but will happily defer) and plan on using that.
* Is it relatively simple to switch DBs midstream? If so, I think starting with whatever is simplest to develop with makes sense and then swapping out as needed when we work on moving from dev to production could work, but given the time frame maybe we don't want to redo that work.

**Comment by whoback** [comment]
- I don't have a pref for host. I've worked with Heroku, AWS, Digital Ocean, Rackspace, etc... If you like the ease of use / support of Heroku I'd suggest giving DO a look lots of "one-click" setups.
- If you want to stick with Heroku it looks like `sqlite` is a no go - good call
- Using SQLAlchemy it is "simple" still another thing to have to think about and config. Would be nice to avoid. We can start with `sqlite` as it is easier to get started with on local.

**Comment by whoback** [comment]
We have the dev version running on sqlite which is supported by Digital Ocean, AWS, Google, Python Anywhere, and a few others. Would be great to just keep as is. I don't think scale will be an issue. Super simple and easy to get other people up to speed. Closing for now.
